//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.5

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

// Add Serialize and Deserialize since they are not include in the generate entity.
// 生成されたエンティティには、SerializeとDeserializeが含まれてないので追加しよう。
#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "user")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(column_type = "Binary(16)", nullable)]
    pub user_id: Option<Vec<u8>>,
    pub name: String,
    pub password: String,
    pub email_address: Option<String>,
    pub create_at: DateTime,
    pub update_at: DateTime,
    pub operation_at: DateTime,
    pub delete_at: Option<DateTime>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
